[package]
authors = ["ololoshka2871"]
name = "stm32-rust-template"
version = "0.1.0"
edition = "2018"
readme = "README.md"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7"

# HAL (will be seectud my feature)
stm32f0xx-hal = { version = "0.18.0", features = ["rt", "stm32-usbd"], optional = true }
stm32l4xx-hal = { git = "https://github.com/stm32-rs/stm32l4xx-hal.git", features = ["rt", "unproven", "stm32-usbd"], tag = "v0.7.1", optional = true  }

# defmt
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2", features = ["print-defmt"] }

[profile.dev.package."*"]
opt-level = "z"

[profile.dev]
opt-level = "z"
lto = false
panic = "abort"

[profile.release]
opt-level = "s"
codegen-units = 1 # better optimizations
debug = true # добавлять отладочные символы. Не влияет на размер исполняемого кода, зато работает дебаг
panic = 'abort'
lto = false # Делает только хуже


[features]
default = [
    "stm32f042", # device

    "defmt-default",
]

stm32f042 = ["stm32f0xx-hal/stm32f042"]

# defmt: do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []