[package]
authors = ["ololoshka2871"]
name = "current-monitor-f0"
version = "0.1.0"
edition = "2018"
readme = "README.md"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"

# HAL
stm32f0xx-hal = { version = "0.18", features = ["rt", "stm32-usbd"] }

# defmt
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2", features = ["print-defmt"] }

#allocator
alloc-cortex-m = "0.4.2"

# ina219
ina219 = "0.1.0"

#usb
usb-device = "0.2.8"
stm32-usbd = "0.6.0"
usbd-serial = { path = "lib/usbd-serial" }

# experimantal
#cmim = "0.2.1" # "move" value to interrupt context

[profile.dev.package."*"]
opt-level = "z"

[profile.dev]
opt-level = "z"
lto = false
panic = "abort"

[profile.release]
opt-level = "s"
codegen-units = 1 # better optimizations
debug = true # добавлять отладочные символы. Не влияет на размер исполняемого кода, зато работает дебаг
panic = 'abort'
lto = false # Делает только хуже


[features]
default = [
    "stm32f042", # mcu

    "defmt-default", # log level
]

# select MCU
stm32f042 = ["stm32f0xx-hal/stm32f042"]

# defmt: do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []