# usage: https://github.com/sagiegurari/cargo-make

[env]
path="target/thumbv6m-none-eabi/debug"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

##############

[tasks.openocd]
command = "openocd"
args = [
    "-f",
    "openocd.cfg",
]

##############

[tasks.flash]
command = "arm-none-eabi-gdb"
args = ["-x", "flash.gdb"]
dependencies = ["build"]
